name: CI/CD Pipeline

on:
  push:
  pull_request:
  pull_request_target:
    types: [closed]
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test:run

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: homeyscripts
          path: dist/
          retention-days: 1

  sync:
    runs-on: ubuntu-latest
    needs: build
    if: >
      (github.event_name == 'pull_request_target' &&
       github.event.pull_request.merged == true &&
       github.event.pull_request.base.ref == 'main' &&
       !contains(github.event.pull_request.merge_commit_message,
                '/skip-sync')) ||
      (github.event_name == 'issue_comment' &&
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '/hsk sync'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        if: github.event_name == 'pull_request_target'
        uses: actions/download-artifact@v4
        with:
          name: homeyscripts
          path: dist/

      - name: Build project
        if: github.event_name == 'issue_comment'
        run: npm run build

      - name: Sync scripts to Homey
        run: >
          npx hsk sync --apiKey ${{ secrets.HOMEY_API_KEY }} --ip ${{
          secrets.HOMEY_IP }} ${{ secrets.HOMEY_HTTPS == 'true' && '--https' ||
          '' }}

      - name: Comment on PR
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ HomeyScripts synced successfully!'
            })
