name: Sync HomeyScripts

on:
  workflow_call:
    inputs:
      download-artifacts:
        description: 'Whether to download build artifacts'
        required: false
        type: boolean
        default: false
      build-if-comment:
        description: 'Whether to build project for issue comments'
        required: false
        type: boolean
        default: false
      comment-on-pr:
        description: 'Whether to comment on PR after sync'
        required: false
        type: boolean
        default: false
    secrets:
      HOMEY_API_KEY:
        required: true
      HOMEY_HOST:
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        if: ${{ inputs.download-artifacts }}
        uses: actions/download-artifact@v4
        with:
          name: homeyscripts
          path: dist/

      - name: Build project
        if: ${{ inputs.build-if-comment }}
        run: npm run build

      - name: Sync scripts to Homey
        run: >
          npx hsk sync --skipConfirmation --apiKey ${{ secrets.HOMEY_API_KEY }}
          --host ${{ secrets.HOMEY_HOST }}

      - name: Comment on PR
        if: ${{ inputs.comment-on-pr }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ HomeyScripts synced successfully!'
            })
